FROM python:latest
WORKDIR /app
COPY . /app
ENV FLASK_APP=flaskr
ENV FLASK_ENV=development
RUN pip install flask
RUN  python3 -m venv .venv
RUN . .venv/bin/activate
RUN pip install e 
RUN flask init-db
EXPOSE 8080
CMD ["flask", "run", "--host=0.0.0.0"]
